stages:
  transform:
    cmd: python src/stages/transform.py --config=params.yaml
    deps:
      - src/stages/transform.py
      - src/utils/transform.py
    params:
      - base
      - transform
    outs:
      - src/data/train_img
      - src/data/train_mask
      - src/data/test_img
      - src/data/test_mask
