base:
  project: road_seg
  random_state: 0

transform:
  raw_dataset_dir: src/data
  raw_dataset_fname: raw_dataset
  train_dir_path: train
  valid_dir_path: valid
  valid_idx:
    - 1
    - 16
    - 17
    - 18
    - 19
    - 20
  patch_size: 256

train:
  batch_size: 16
  num_epoch: 10
  lr: 0.001
  model_pickle_fpath: models/model_pickle.pkl
  augmentations: {p_flip_honz: 0.5, p_flip_vert: 0.5, max_rotate: 35.0, p_rotate: 1.0}
  training_tmp_output_base_fpath: src/training
